### ISSUE TITLE
Really interested in Health-LLM

### ISSUE THREAD

**Issue by nickorlabs** [MingyuJ666/The-Impact-of-Reasoning-Step-Length-on-Large-Language-Models#2]
Paper sent me to your repositories but alas no HealthLLM :( 

https://github.com/jmyissb/HealthLLM

Would love to talk about this and some focused ideas on Health and LLMs Please!

**Comment by MingyuJ666** [comment]
ok， how can we talk about it. The code has some problems now

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/02/2024 13:48 |
| To | jmyissb/The-Impact-of-Reasoning-Step-Length-on-Large-Language-Models ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [jmyissb/The-Impact-of-Reasoning-Step-Length-on-Large-Language-Models] Really interested in Health-LLM (Issue #2) |

Paper sent me to your repositories but alas no HealthLLM :(

https://github.com/jmyissb/HealthLLM

Would love to talk about this and some focused ideas on Health and LLMs Please!

**Comment by nickorlabs** [comment]
Ahh ok!  Umm not sure if you have Discord, my ID is savethedoctor?  Also, really enjoyed the research in "AttackEval: How to Evaluate the Effectiveness of Jailbreak Attacking on Large Language Models" Being in Cybersecurity.  Looking forward to connecting, if you have other ideas than Discord let me know!!

**Comment by MingyuJ666** [comment]
ok i will download it， and i will reach you tonight

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/02/2024 17:19 |
| To | jmyissb/The-Impact-of-Reasoning-Step-Length-on-Large-Language-Models ***@***.***> |
| Cc | jmy ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [jmyissb/The-Impact-of-Reasoning-Step-Length-on-Large-Language-Models] Really interested in Health-LLM (Issue #2) |

Ahh ok! Umm not sure if you have Discord, my ID is savethedoctor? Also, really enjoyed the research in "AttackEval: How to Evaluate the Effectiveness of Jailbreak Attacking on Large Language Models" Being in Cybersecurity. Looking forward to connecting, if you have other ideas than Discord let me know!!

**Comment by MingyuJ666** [comment]
i just add you
